P=[1 1 -1 -1; 1 -1 1 -1];
T=[1 -1 1 -1];
plot(P, T);
net = newff([-1 1;-1 1],[1 1],{'hardlims' 'hardlims'} );
net.iw{1,1}=[0.4772 0.5121];
net.b{1}=[0];
net = train(net,P,T);
pesos = net.iw{1,1};
bias = net.b{1};
plotpc(pesos,bias);
en = [0.6 ;0.4];
y = sim(net,en);
plot(en,y);
hold on;
point = findobj(gca,'type','line');
set(point,'Color','red');
plot(P,T);
plotpc(pesos,bias);
hold off;